# Generated by Django 4.1.2 on 2022-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0003_book_is_published_chef_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="main_image",
            field=models.ImageField(
                null=True, upload_to="media/foods_main/", verbose_name="Main Photo"
            ),
        ),
    ]
