# Generated by Django 4.1.2 on 2022-10-29 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0004_food_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="burger.category",
                verbose_name="category",
            ),
        ),
    ]
