# Generated by Django 4.1.2 on 2022-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0005_alter_food_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(max_length=200, null=True, verbose_name="Icon"),
        ),
    ]
