# Generated by Django 4.1.2 on 2022-10-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0006_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="is_published"
            ),
        ),
        migrations.AlterField(
            model_name="book", name="time", field=models.TimeField(),
        ),
    ]
