# Generated by Django 4.1.2 on 2022-10-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("burger", "0008_alter_book_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("url", models.SlugField(max_length=200, verbose_name="URL")),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(upload_to="media/BlogFood", verbose_name="Photo"),
                ),
                (
                    "time_create",
                    models.DateField(auto_now_add=True, verbose_name="Creat Time"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Published"
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burger.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={"verbose_name": "Blog", "verbose_name_plural": "Blogs",},
        ),
    ]
